name: CD

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  build:
    uses: omarshaarawi/fantasy-football-jvm/.github/workflows/gradle.yml@main
    secrets:
      username: ${{ secrets.GIT_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          USERNAME: ${{ secrets.GIT_USERNAME }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.release.tag_name }}
